### PR TITLE
Add reference documentation about Vulnerability Management #109

### PR DESCRIPTION
**Pull request by tdruez**
https://github.com/aboutcode-org/dejacode/issues/109

The current progress is published at https://dejacode.readthedocs.io/en/109-vulnerability-documentation/reference-vulnerability-management.html

### CODE REVIEW

**Comment by DennisClark** [comment]
@tdruez   Very impressive additions to the documentation, which is nicely comprehensive.  I do not have any suggestions or corrections at this time.

**Comment by tdruez** [comment]
@DennisClark In addition to the "Vulnerability Management" chapter, I've added a new How To about "Product Vulnerability Analysis".

Available at https://dejacode.readthedocs.io/en/109-vulnerability-documentation/howto-4-product-vulnerability-analysis.html for review. This should complete the https://github.com/aboutcode-org/dejacode/issues/109 scope.

**Comment by DennisClark** [comment]
@tdruez  Perhaps it would be nice to add the following "Note" at the end of the "3. Conducting Analysis" section: 

The analysis details that you provide for a product package vulnerability are included in the "vulnerabilities" sections of the CycloneDX SBOM+VEX 1.6 and VEX 1.6 documents when you share them from your products.

**Comment by DennisClark** [comment]
@tdruez   The new "How To" is very nice and comprehensive; I have no additional suggestions beyond the two comments above.

**Pull request merged**
